### ISSUE TITLE
any code? 

### ISSUE THREAD

**Issue by nullarch** [jamessealesmith/continual-diffusion#1]
I'd like to try it out, but do you have any plans to officially release the code soon?

**Comment by ahmadmustafaanis** [comment]
yes pls

**Comment by dgr9527** [comment]
> 

cheer

**Comment by jamessealesmith** [comment]
Feel free to contact me directly at jamessealesmith at gatech dot edu

**Comment by jamessealesmith** [comment]
Thank you very much for the interest in our work :)
